### ISSUE TITLE
Please update to support Python 3

### ISSUE THREAD

**Issue by kraftpunk97** [jgorset/fandjango#113]

**Comment by jgorset** [comment]
Hi @kartikeygupta! We're not using Python 3 or Fandjango at the moment, but if you need it we'd be happy to accept a pull request!

**Comment by kartikeygupta** [comment]
@jgorset. I would definitely like to submit a pull request. Thanks😃!

**Comment by jgorset** [comment]
Sure thing, @kartikeygupta! I haven't worked much with Python 3 myself, but feel free to post in this thread and if I don't know I'm sure someone else does.

**Comment by kartikeygupta** [comment]
Sorry for the long message.

@jgorset , I think I have fixed some of the code that needed an upgrade, but I'm kind of stuck. I'm tried to install the module on my system using the `setup.py` file.
1) It got installed in the same directory where I placed the `setup.py` file and not in the site-packages folder. How do I set the default install directory to the `site-packages`?
2) Total of 4 folders were created. `build, dist, fandjango and one more (I'm sorry I didn't note down the name of the folders before deleting them.)
3)  When importing the module, it displays an error while processing the `admin` file, for `from models import User, OAuthToken` command. I tried googling more about this `models` module. I know that it related to the django module, but I couldn't find the `Users` and `OAuthToken` objects in its source code. I was wondering if you could tell me more about it, so that I have a better idea about what to look for.

Thanks :D!

**Comment by JordenLCH** [comment]
also need that for python3 

will be glad if someone port it to python3

thanks
